import { MDXRemote } from "next-mdx-remote/rsc"
import React from "react"

import { loadBlogPost } from "@/helpers/file-helpers"
import COMPONENT_MAP from "@/helpers/mdx-components"

import styles from "./BlogPost.module.css"

export type BlogPostParams = {
  params: { postSlug: string }
}

async function BlogPost({ params }: BlogPostParams) {
  const { frontmatter, content, headings } = await loadBlogPost(params.postSlug)
  const { title, chatGPTPrompt } = frontmatter

  const renderHeadings = (): Array<String> => {
    const headingsList: Array<String> = []
    headings.map((item) => {
      if (item.level === 2) {
        headingsList.push(
          <li className={styles.tocH2} key={item.title}>
            <h2>{item.title}</h2>
          </li>
        )
      } else if (item.level === 3) {
        headingsList.push(
          <li className={styles.tocH3} key={item.title}>
            <h3>{item.title}</h3>
          </li>
        )
      }
    })
    return headingsList
  }

  console.log("HEADINGS", headings)

  return (
    <main className={styles.wrapper}>
      <section className={styles.blogHero}>
        <h1 className={styles.blogTitle}>{title}</h1>
        <p className={styles.disclaimer}>
          Note: this post was <strong>generated by ChatGPT</strong> with the
          prompt &ldquo;{chatGPTPrompt}.&rdquo; The quality of this post is
          questionable at best.
        </p>
      </section>
      <div className={styles.container}>
        <section className={styles.content}>
          <MDXRemote source={content} components={COMPONENT_MAP} />
        </section>
        <section className={styles.toc}>
          <h1>Contents</h1>
          <ul className={styles.toc}>{renderHeadings()}</ul>
        </section>
      </div>
    </main>
  )
}

export default BlogPost
